config/routes.rb
Rails.application.routes.draw do

  # use rake routes in order to see your routes so far

  get 'main_page/index'
  # routes notes:
  # formats:
  # root 
  # regular route format is get '<pageName>' => '<controller>#<function>'
  # get '<THIS PART>' is incidentally the name of the link usually (e.g. in html.erb) this is the link_to "<Text that user sees>", <THIS PART>_path
  # this is also (probably) the name of the method found @ the controller 
  # finally, you can give these custom names if you wish to be pointed at easier (as: part)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'products/search' => 'products#search', as: 'search_products'
  get 'orders/search' => 'orders#search', as: 'search_orders'
  get 'ordersummary' => 'ordersummary#index'
  
  # signup routes
  get 'users' => 'users#new', as: 'signup'
  
  get 'logout' => 'sessions#logout'
###############################################################################################################
  # let's try some manual routing for details
  # get 'details' => 'main_page#show'
  # get '/details', controller: 'main_page', action: 'show' # this is the sprawled out version of get 'details' => 'main_page#show'
  # this is actually some method
  # get('/details', {:controller => 'main_page', :action => 'show'}) # this is the non-railsified way
  
  #but we need it to be dynamic
  get '/mainpage/search' => 'main_page#index', as: 'main_search'
  get '/items/:id' => 'main_page#show', as: 'item' # this is where we go when we click an item from the front page
  

  get '/cart' => 'cart#show', as: 'cart'
  post '/cart/save' => 'cart#save_cart', as: 'save_cart'
  post '/cart/checkout' => 'cart#checkout', as: 'checkout'
  post '/orders/:id' => 'order#checkout', as: 'confirm_checkout'
  post '/cart' => 'cart#rmv_cart_atindex', as: 'rmv_cart_atindex'
  put '/cart' => 'cart#addToCart', as: 'add_to_cart'

###############################################################################################################
  post '/items' => 'main_page#dosloginfirstflash', as: 'dos_must_be_logged'
  
  get '/items' => 'main_page#loginfirstflash', as: 'must_be_logged'

  root 'main_page#index'

  resources :products
  resources :orders
  resources :users
  resources :sessions
end

app/models/cart.rb
class Cart
# this class handles the Cart
    include Mongoid::Document
    cartContents = []
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    def show
        @counter = 0 # starting counter num
        @order = Order.new
        if session[:user_id] != nil
            @cart = User.find_by(userid: session[:user_id]).cart
            puts "[cart_controller] cartcontents: " +@cart.to_s
        elsif
            redirect_to root_url
        end
    end

    def addToCart
        prodcode = params[:prodCode]
        qty = params[:qty]

        if qty != nil && qty.to_i > 0
            ar = [prodcode, qty.to_i]
            @usercart = User.find_by(userid: session[:user_id])
            puts "[cart_controller] user cart 1 %s " % @usercart.cart.to_s
            # @usercart.add_to_set(cart: [ar])
            @usercart.cart.push(ar)
            @usercart.save
            puts "[cart_controller] user cart 2 %s " % @usercart.cart.to_s
            puts "[cart_controller] <%s> prod" % prodcode
            puts "[cart_controller] at least you made it. %d " % qty.to_s
            puts "[cart_controller] added to your cart: %s " % ar.to_s
            redirect_back(fallback_location: :back)
        else
            puts "[cart_controller] illegal amount "
            redirect_back(fallback_location: :back)
        end

    end

    def save_cart
        puts "[cart_controller] params[:qty] is: %d " % params[:qty]
        puts "[cart_controller] params[:indx] is: %d " % params[:indx]
        y = params[:indx].to_i - 1
        qty = params[:qty]
        @user = User.find_by(userid: session[:user_id])
        puts "[cart_controller] before: %s " % @user.cart.to_s
        @user.cart[y][1] = qty.to_i
        puts "[cart_controller] after: %s " % @user.cart.to_s
        @user.save

        redirect_back(fallback_location: :back) # returns you to the cart page
    end

    def addToCart_dupe #dupe
        prodcode = params[:prodCode]
        qty = params[:qty].to_i
        ar = [prodcode, qty]
        @usercart = User.find_by(userid: session[:user_id])
        puts "[cart_controller] user cart 1 %s " % @usercart.cart.to_s
        @usercart.add_to_set(cart: [ar])
        puts "[cart_controller] user cart 2 %s " % @usercart.cart.to_s
        puts "[cart_controller] <%s> prod" % prodcode
        puts "[cart_controller] at least you made it. %d " % qty.to_s
        puts "[cart_controller] added to your cart: %s " % ar.to_s

        redirect_back(fallback_location: :back)
    end
    # x.delete_at(x.index 2)

    def removeFromCartIndex
        @user = User.find_by(userid: session[:user_id])
        redirect_back(fallback_location: :back)
    end

    def total_price(oC)
        # @pc = Pricecalc.new(oC)
        return Ordrcontentgetter.total_price(oC)
    end
    helper_method :total_price

    def rmv_cart_atindex
        puts "????????????????????????????????????????????????????"
        puts "[cart_controller] deleting a cart entry %s" % params[:index].to_s
        @user = User.find_by(userid: session[:user_id])
        @user.cart.delete_at(params[:index].to_i)
        @user.save
        redirect_back(fallback_location: :back)
    end

    def checkout
        if session[:user_id] != nil
            puts "[cart_controller] checking out."
            @user = User.find_by(userid: session[:user_id])
            
            ## construction of the order
            #orderCode
            genCode = ''
            if Order.last() == nil
                genCode = 'O00001'
            else
                prevOrd = Order.last().orderCode[1..5].to_i
                prevOrd = prevOrd +1
                genCode = 'O' +prevOrd.to_s.rjust(5, "0")
            end
            #orderDate /dateStr
            date ||= Date.today
            #orderUser
                #take from @user.userid
            #~user~ cart extraction and setting of order to user
            @user.add_to_set(orders:genCode)
            newOrderContent = @user.cart
            empty_cart(@user)
            #orderNames
                # done by get_names()
            # @order = Order.new(order_params(genCode, ))
            @order = Order.new(:orderCode => genCode, :orderDate => date, :orderDateStr => date.to_s, :orderUser => @user.userid, :orderNames => get_names(newOrderContent), :orderContents => newOrderContent)
            @order.save

            redirect_to confirm_checkout_path(id:@order._id), notice: 'Transaction Authorized. Thank you!'
        elsif
            redirect_to root_url 
        end
    end

    private
        def empty_cart(user)
            user.cart = []
            user.save
        end

        def add_cart(user, added) # for singular
            user.cart = [added]
            # user.save
        end
        
        def fill_order(order, newcart) # for multiple
            order.orderContent = newcart
            # order.save
        end

        def order_params
            params.require(:order).permit(:orderCode, :orderDate, :orderUser, :orderContent, :orderNames)
        end


        def get_names(oC)
          names = []
          orderContents = oC
          orderContents.each do |item|
              prods = Product.where(:prodCode => item[0])
              prods.each do |p|
                  names.push("[%dx]" % [item[1].to_i] +p.prodName)  
              end
          end
          return names.join(", ")
      end
end

app/views/cart/show.html.erb
<div id="orderSummary" class="orderSummary" style="margin-top:5%;">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-7 col-sm-7" >
            <h1>Your Cart</h1>
            <% @cart.each do |item| %>
                <% @product = Product.find_by(:prodCode => item[0]) %>
                            <% @counter+=1 %>
                <div class="container" style="border: 2px solid #aaa; outline: none; box-sizing: border-box; height:40%; margin-top:10px;">
                    <div class="row">
                        <div class="col-lg-4 col-md-4" style="height:140px;width:100%;">
                            <%= image_tag(@product.pathToImg, size:"200x140") %>
                        </div>
                        <div class="col-lg-4 col-md-4"> <!-- stylize this more -->
                            <i><%= @product.prodCategory %></i>
                            <h4><%= @product.prodName %></h4>
                            <p><%= @product.prodDesc %></p>
                            <p><%= number_to_currency(@product.price, :unit => '₱') %></p><br/>
                            <!-- ############################################################################################# -->
                            <%= form_tag save_cart_path, method: :post do %>
                            <b> <%# text_field_tag (:qty, item[1].to_i, :disabled => true, :name => "qtyfield"+@counter.to_s) %></b>
                            <%# strtosym = "qtyfield"+@counter.to_s %>
                            <%# puts strtosym %>
                            <b>Qty: <%= text_field_tag(:qty,item[1].to_i,disabled:true, data:{tryhardID: @counter})%></b>
                            <div class="btn-group">
                                <!-- comment out this Save button once the rails ver is here -->
                                <!--<button type="button" class="btn" style="visibility: hidden" onclick="cloak(this)" name="bSave<%= @counter %>" data-bindex=<%= @counter %>>Save</button>-->
                                <%# button_to "Save", save_cart_path, data:{bindex:@counter.to_s}, params:{indx:@counter-1}, class:"btn", style:"visibility: hidden", onclick:"cloak(this)", name:"bSave"+@counter.to_s %>
                                <%= hidden_field_tag 'indx', @counter %>
                                <%= submit_tag "Save", data:{bindex:@counter.to_s, save:1}, params:{indx:@counter-1}, class:"btn", style:"visibility: hidden", onclick:"cloak(this)", name:"bSave"+@counter.to_s %>
                            <% end %>
                            <!-- ############################################################################################# -->
                                <button type="button" class="btn" style="visibility: hidden" onclick="cloak(this)" name="bCancel<%= @counter %>" data-save=0 data-bindex=<%= @counter %> >Cancel</button>
                            </div>
                            <!--:qty, id: :qty, :readonly=>true, value:item[1].to_s-->
                            <!--item[1].to_i -->
                        </div>
                        <div class="col-lg-4 col-md-4">
                           <!--<button type="button" class="btn btn-danger btn_destroy" style="margin-top:50px;float:right;">Remove</button>-->
                           <% puts @counter.to_s + "HAHAHA" %>
                           <%= link_to "Delete", rmv_cart_atindex_path, params:{index: @counter-1}, class:"btn btn-danger btn_destroy", style:"margin-top:50px;float:right;", name:"bDelete" %>
                           <!-- edit button will reveal two buttons save and cancel, function name explanatory -->
                           <button type="button" class="btn btn-primary btn_edit" style="margin-top:50px;float:right;" onclick="decloak(this)" name="bEdit" data-bindex=<%= @counter %>>Edit</button>
                           
                           <!--<%= button_to "Edit", cart_path, :method => "get", params:{index: @counter}, class:"btn btn-primary btn_edit", style:"margin-top:50px;float:right;"  %>-->
                        </div>
                    </div>
                </div>
                <br/>
                <% end %>
        </div>

        <div class="col-lg-5 col-md-5 col-sm-5 " id="rightPanel">
            <h1>Total</h1>
            <table class = 'table table-condensed table-hover'>
                <thead>
                    <tr>
                    <th>Qty</th> 
                    <th>Name</th> 
                    <th>Price</th> 
                    <th colspan="3"></th> 
                    </tr>
                </thead>
                <tbody>
                    <% @cart.each do |item| %>
                    <% @product = Product.find_by(:prodCode => item[0]) %>
                    <tr>
                    <td><%= item[1].to_i %></td> 
                    <td><%= @product.prodName %></td> 
                    <td><%= number_to_currency((@product.price * item[1]), :unit =>'₱') %> </td>
                    </tr>
                    <% end %> 
                </tbody>
            </table>
            <h3 style="margin-top:60%;margin-left:50%;">Total: <%= number_to_currency(total_price(@cart), :unit => '₱') %></h3>
            <!--<button type="button" class="btn btn-danger btn_destroy" style="float:right;">Cancel</button>-->
            <%= link_to 'Back', :back, class:"btn", style:"float:right;" %>
            <!--<button type="button" class="btn btn-new btn_new" style="float:right;">Check Out</button>-->
            <%= button_to "Check out", checkout_path, data: { confirm: "Authorize Transaction?"}, params:{ :id => "O00001"}, class:"btn btn-new btn_new", style:"float:right;" %>
        </div>
            
        </div>
    </div>
</div>

<script>
    function decloak(button)
    {
        var edit_button = document.getElementsByName("bEdit");
        var delete_button = document.getElementsByName("bDelete");
        
        for(var i = 0; i < edit_button.length; i++)
        {
            edit_button[i].disabled = true;
            delete_button[i].disabled = true;
        }
        var save_button = document.getElementsByName("bSave"+button.dataset.bindex.toString());
        var cancel_button = document.getElementsByName("bCancel"+button.dataset.bindex.toString());
        var qtyfield = document.getElementsByName("qty");
        qtyfield[button.dataset.bindex-1].disabled = false;
        save_button[0].style.visibility = "visible";
        cancel_button[0].style.visibility = "visible";
    }
    function cloak(button)
    {
        var edit_button = document.getElementsByName("bEdit");
        var delete_button = document.getElementsByName("bDelete");
        for(var i = 0; i < edit_button.length; i++)
        {
            edit_button[i].disabled = false;
            delete_button[i].disabled = false;
        }
        var save_button = document.getElementsByName("bSave"+button.dataset.bindex.toString());
        var cancel_button = document.getElementsByName("bCancel"+button.dataset.bindex.toString());
        var qtyfield = document.getElementsByName("qty");
        qtyfield[button.dataset.bindex-1].disabled = button.dataset.save == 1 ? false : true;
        save_button[0].style.visibility = "hidden";
        cancel_button[0].style.visibility = "hidden";
    }
</script>