config/routes.rb
Rails.application.routes.draw do

  # use rake routes in order to see your routes so far

  get 'main_page/index'
  # routes notes:
  # formats:
  # root 
  # regular route format is get '<pageName>' => '<controller>#<function>'
  # get '<THIS PART>' is incidentally the name of the link usually (e.g. in html.erb) this is the link_to "<Text that user sees>", <THIS PART>_path
  # this is also (probably) the name of the method found @ the controller 
  # finally, you can give these custom names if you wish to be pointed at easier (as: part)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'products/search' => 'products#search', as: 'search_products'
  get 'orders/search' => 'orders#search', as: 'search_orders'
  get 'ordersummary' => 'ordersummary#index'
  
  # signup routes
  get 'users' => 'users#new', as: 'signup'
  
  get 'logout' => 'sessions#logout'
###############################################################################################################
  # let's try some manual routing for details
  # get 'details' => 'main_page#show'
  # get '/details', controller: 'main_page', action: 'show' # this is the sprawled out version of get 'details' => 'main_page#show'
  # this is actually some method
  # get('/details', {:controller => 'main_page', :action => 'show'}) # this is the non-railsified way
  
  #but we need it to be dynamic
  get '/mainpage/search' => 'main_page#index', as: 'main_search'
  get '/items/:id' => 'main_page#show', as: 'item' # this is where we go when we click an item from the front page
  

  get '/cart' => 'cart#show', as: 'cart'
  post '/cart/save' => 'cart#save_cart', as: 'save_cart'
  post '/cart/checkout' => 'cart#checkout', as: 'checkout'
  post '/orders/:id' => 'order#checkout', as: 'confirm_checkout'
  post '/cart' => 'cart#rmv_cart_atindex', as: 'rmv_cart_atindex'
  put '/cart' => 'cart#addToCart', as: 'add_to_cart'

###############################################################################################################
  post '/items' => 'main_page#dosloginfirstflash', as: 'dos_must_be_logged'
  
  get '/items' => 'main_page#loginfirstflash', as: 'must_be_logged'

  root 'main_page#index'

  resources :products
  resources :orders
  resources :users
  resources :sessions
end

app/models/order.rb
class Order
  include Mongoid::Document
  include Mongoid::Timestamps
  field :orderCode, type: String    # code of order
  field :orderDate, type: DateTime      # date when order was made
  field :orderDateStr, type: String, default: -> { orderDate.to_s }
  field :orderUser, type: String    # user who made order
  field :orderNames, type: String
  field :orderContents, type: Array, default: []     # order's contents (prodCode and quantity)
  field :deleted, type: Boolean, default: false
  # field :_id, type: String, default: -> { orderCode.to_s.parameterize } # this makes it so the link above would be reflected here 

  def isDeleted?
    deleted == true
  end

  def product_list=(arg)
    self.orderContents = arg.split(',').map { |v| v.strip }
  end 

  def product_list
    self.orderContents.join(', ')
  end

  def self.search(search) #basically for admin
    if search
      any_of({orderUser: /#{search}/i},{orderNames: /#{search}/i})
    end
  end

  def self.searchFiltered(search, userid)
    
    if search
      where(orderNames:/#{search}/i , orderUser: userid)
    end
  end

  

  def minusOne(inp) #nothing but a test method
    return inp-1
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  
  # GET /orders
  # GET /orders.json
  def index
    sleep 1
    # @orders = Order.all
    if session[:user_id] == nil
      redirect_to root_url
    elsif session[:is_admin]
      if params[:search].blank?
        @orders = Order.all
      else
        @orders = Order.search(params[:search])
        
      end
    else # filtered for user only
      if params[:search].blank?
        @orders = Order.where(orderUser: session[:user_id])
      else
        @orders = Order.searchFiltered(params[:search], session[:user_id])
        
      end
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    if session[:user_id] == nil
        redirect_to root_url
    end
  end

  # GET /orders/new
  def new
    # puts "[orders_controller] New Order"
    if session[:user_id] == nil
      redirect_to root_url

    end
    @order = Order.new
    if Order.last() == nil
      puts "[order_controller] db.order empty, first code generated"
      @genCode = '00001'
    else
      @prevOrd = Order.last().orderCode[1..5].to_i
      @prevOrd = @prevOrd +1
      @genCode = @prevOrd.to_s.rjust(5, "0")
    end
  end

  # GET /orders/1/edit
  def edit
    # @genCode = @product.prodCode
    if session[:user_id] == nil
      redirect_to root_url
    end
  end

  # POST /orders
  # POST /orders.json
  def create
    
    puts "[orders_controller] Create Order"
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.deleted = true
    @order.update_attributes(:deleted => true)  
    # @order.destroy
    respond_to do |format|
      format.html { redirect_to order_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def total_price(oC)
    # @pc = Pricecalc.new(oC)
    return Ordrcontentgetter.total_price(oC)
  end
  helper_method :total_price
  
  def get_names(oC)
    return Ordrcontentgetter.get_names(oC)
  end
  helper_method :get_names

   
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:orderCode, :orderContents)
    end
end

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<!-- This is what a user would see when they want to review their orders -->
<div class="container">
  <br/>
  <h1>Order History</h1>
  <div id="header" class="header">
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <%= form_tag orders_path, :method => 'get' do %>
            <!--<button type="button" id="SearchButton" class="btn">Search</button>
            <input type="text" id="search" name="search" class="SearchBar" placeholder="Search">-->
            <%= text_field_tag :search, params[:search], placeholder:'Search...' %>
            <%= button_tag "Search", name: nil, class:'btn'%>
          <% end %>
        </div> 
      </div>   
  </div> 
  <table class = 'table table-condensed table-hover'>
    <thead>
      <tr>
        <th>Order No.</th> 
        <th>Date Ordered</th>
        <th>Contents</th> 
        <th>Total Price</th> 
        <th colspan="3"></th> 
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <% if not order.isDeleted? %>
            <tr>
              <td><%= order.orderCode %></td> 
              <td><%= order.orderDate %></td> 
              <td><%= shorten(get_names(order.orderContents), 40) %></td> 
              <!-- total order price at this part --> 
              <%# order.orderContents.each do |item|%> 
                <%# total_price += price[1] %> 
              <%# end %> 
              <% puts "[index.html-orders] " + total_price(order.orderContents).to_s %> 
              <td><%= number_to_currency(total_price(order.orderContents), :unit =>'P') %> </td> 
              <td>
              <%= link_to 'Show', order, class:'btn'%>
              <%# link_to 'Edit', edit_order_path(order), class:'btn btn-primary btn_edit' %>
              <%# link_to 'Delete', order, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn_destroy' %>
              </td>
            </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

<br>

<%# The syntax here is link_to 'Text user sees', actual link, 'further items here are other attributes on the tag' %>

</div>

app/views/orders/show.html.erb
<div id="orderSummary" class="orderSummary" style="margin-top:5%;">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-7 col-sm-7" >
            <h1>
                <% if session[:is_admin] %>
                    Order: <%= @order.orderCode %>
                <% else %>
                    Your Order
                <% end %>

                
            </h1>
            <% @order.orderContents.each do |item| %>
                <% @product = Product.find_by(:prodCode => item[0]) %>
                <div class="container" style="border: 2px solid #aaa; outline: none; box-sizing: border-box; height:40%; margin-top:10px;">
                    <div class="row">
                        <div class="col-lg-4 col-md-4" style="height:140px;width:100%;">
                            <%= image_tag(@product.image_url.to_s, size:"200x140") %>
                        </div>
                        <div class="col-lg-4 col-md-4"> <!-- stylize this more -->
                            <i><%= @product.prodCategory %></i>
                            <h4><%= @product.prodName %></h4>
                            <p><%= @product.prodDesc %></p>
                            <p><%= number_to_currency(@product.price, :unit => '₱') %></p><br/>
                            <p>Qty: <%= item[1].to_i %></p>
                        </div>
                        <div class="col-lg-4 col-md-4">
                           <!--<button type="button" class="btn btn-danger btn_destroy" style="margin-top:50px;float:right;">Remove</button>-->
                        </div>
                    </div>
                </div>
            <% end %>
            </div>
            <div class="col-lg-5 col-md-5 col-sm-5 " id="rightPanel">
                <h1>Total</h1>
                 <table class = 'table table-condensed table-hover'>
                    <thead>
                      <tr>
                        <th>Qty</th> 
                        <th>Name</th> 
                        <th>Price</th> 
                        <th colspan="3"></th> 
                      </tr>
                    </thead>
                     <tbody>
              <% @order.orderContents.each do |item| %>
              <% @product = Product.find_by(:prodCode => item[0]) %>
            <tr>
              <td><%= item[1].to_i %></td> 
              <td><%= @product.prodName %></td> 
              <td><%= number_to_currency((@product.price * item[1]), :unit =>'₱') %> </td>
            </tr>
              <% end %> 
            
    </tbody>
                
                     
                </table>
                <h3 style="margin-top:60%;margin-left:50%;">Total: <%= number_to_currency(total_price(@order.orderContents), :unit => '₱') %></h3>
                <!--<button type="button" class="btn btn-danger btn_destroy" style="float:right;">Cancel</button>-->
                <%= link_to 'Back', orders_path, class:'btn btn-danger btn_destroy', style:"float:right;" %>
                
            </div>
            
        </div>
    </div>
</div>