config/routes.rb
Rails.application.routes.draw do

  # use rake routes in order to see your routes so far

  get 'main_page/index'
  # routes notes:
  # formats:
  # root 
  # regular route format is get '<pageName>' => '<controller>#<function>'
  # get '<THIS PART>' is incidentally the name of the link usually (e.g. in html.erb) this is the link_to "<Text that user sees>", <THIS PART>_path
  # this is also (probably) the name of the method found @ the controller 
  # finally, you can give these custom names if you wish to be pointed at easier (as: part)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'products/search' => 'products#search', as: 'search_products'
  get 'orders/search' => 'orders#search', as: 'search_orders'
  get 'ordersummary' => 'ordersummary#index'
  
  # signup routes
  get 'users' => 'users#new', as: 'signup'
  
  get 'logout' => 'sessions#logout'
###############################################################################################################
  # let's try some manual routing for details
  # get 'details' => 'main_page#show'
  # get '/details', controller: 'main_page', action: 'show' # this is the sprawled out version of get 'details' => 'main_page#show'
  # this is actually some method
  # get('/details', {:controller => 'main_page', :action => 'show'}) # this is the non-railsified way
  
  #but we need it to be dynamic
  get '/mainpage/search' => 'main_page#index', as: 'main_search'
  get '/items/:id' => 'main_page#show', as: 'item' # this is where we go when we click an item from the front page
  

  get '/cart' => 'cart#show', as: 'cart'
  post '/cart/save' => 'cart#save_cart', as: 'save_cart'
  post '/cart/checkout' => 'cart#checkout', as: 'checkout'
  post '/orders/:id' => 'order#checkout', as: 'confirm_checkout'
  post '/cart' => 'cart#rmv_cart_atindex', as: 'rmv_cart_atindex'
  put '/cart' => 'cart#addToCart', as: 'add_to_cart'

###############################################################################################################
  post '/items' => 'main_page#dosloginfirstflash', as: 'dos_must_be_logged'
  
  get '/items' => 'main_page#loginfirstflash', as: 'must_be_logged'

  root 'main_page#index'

  resources :products
  resources :orders
  resources :users
  resources :sessions
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  def index
    @cupcakes_flag = false
    @cakes_flag = false
    @cookies_flag = false
    @bread_flag = false
    @brownies_flag = false
    # we're gonna need to have some flags here to determine what results will appear.
    if params[:search].blank?
      # @products = Product.all.paginate(:page => params[:page], :per_page => 10)
      @products = Product.all
      @products.each do |product|
        if product.prodCategory.casecmp("Cupcakes") == 0 
          if !@cupcakes_flag # has never been true before
            @cupcakes_flag = true 
          end
        end
        if product.prodCategory.casecmp("Cookies") == 0 
          if !@cookies_flag # has never been true before
            @cookies_flag = true 
          end
        end
        if product.prodCategory.casecmp("Cakes") == 0 
          if !@cakes_flag # has never been true before
            @cakes_flag = true
          end
        end
        if product.prodCategory.casecmp("Bread") == 0 
          if !@bread_flag # has never been true before
            @bread_flag = true 
          end
        end
        if product.prodCategory.casecmp("Brownies") == 0 
          if !@brownies_flag # has never been true before
            @brownies_flag = true 
          end
        end
      end
    else
      # @products = Product.search(params[:search]).paginate(:page => params[:page], :per_page => 10)
      @products = Product.search(params[:search])
     
      @products.each do |product|
        if product.prodCategory.casecmp("Cupcakes") == 0 
          if !@cupcakes_flag # has never been true before
            @cupcakes_flag = true 
          end
        end
        if product.prodCategory.casecmp("Cookies") == 0 
          if !@cookies_flag # has never been true before
            @cookies_flag = true 
          end
        end
        if product.prodCategory.casecmp("Cakes") == 0 
          if !@cakes_flag # has never been true before
            @cakes_flag = true
          end
        end
        if product.prodCategory.casecmp("Bread") == 0 
          if !@bread_flag # has never been true before
            @bread_flag = true 
          end
        end
        if product.prodCategory.casecmp("Brownies") == 0 
          if !@brownies_flag # has never been true before
            @brownies_flag = true 
          end
        end
      
      end
    @cart = Cart.new
  end
    # GET /products/1
  # GET /products/1.json
  def show
    puts "[main_page_controller] Found prodCode: " +params[:id].to_s
    # we're receving a params[:id] from the outside. (e.g. /item/1 <- 1 is the :id)
    @product = Product.find_by(prodCode: params[:id])
    @cart = Cart.new
    
  end
  
  def loginfirstflash
    puts "[main_page_controller] action attempted before login. denied"
    flash[:notice] = "Please Login first"
    redirect_back(fallback_location: :back)
  end

  def dosloginfirstflash
    puts "[main_page_controller] action attempted before login. denada"
    flash[:notice] = "Please Login first"
    # redirect_back(fallback_location: :back)
    @event = Event.find(params[:id])
    respond_to do |format|
      format.js
    end
    
  end
end
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/main_page/_formsignup.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <%= pluralize(product.errors.count, "error") %> prohibited this user from being saved:
      </div>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li> <%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# temporary field, this is just to show what their userid would be %>
  <div class="field">
    <%= form.label 'Userid' %>
    <%= form.text_field :userid, id: :user_userid, :readonly=>true, class:'form-control' , value:@genCode%>
  </div>

  <div class="field">
    <%= form.label 'Username' %>
    <%= form.text_field :username, id: :user_username, class:'form-control' %>
  </div>

  <div class="field">
    <%= form.label 'Password' %>
    <%= form.password_field :password, id: :user_password, class:'form-control' %>
  </div>
  <!--temporarily hide confirm, cant get it to work yet-->
  <!--<div class="field">-->
    <%# form.label 'Confirm Password' %>
    <%# form.password_field :password_confirmation, id: :user_password_confirmation, class:'form-control' %>
  <!--</div>-->
  <div class="actions">
    <%= form.submit 'Sign up!', class:'btn btn_new'%>
  </div>
<% end %>

app/views/main_page/index.html.erb
<!-- everyone can see this page -->
<div id="header" class="header" >
    <div class="logo">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <br>
                <br>
                <%= image_tag("Sliders/SliderImage1",size:"720x400") %>              
            </div>
        </div>
    </div>
</div>


<div id="thumbnail" class="thumbnail" style="margin-top:2%;">
  <div class="container-fluid">
    <!-- flesh this out more some time, integrate search function -->
      <% if @cakes_flag %>
      <h2>Cakes</h2>
      <% end %>
      <div class="row text-center text-lg-left">
      <% @products.each do |product| %>
        <% if not product.isDeleted? %>
          <% if product.prodCategory.casecmp("Cakes") == 0 %>
            <div class="col-lg-3 col-md-3 col-xs-6">
              <%= link_to item_path(product.prodCode), :class => "d-block mb-4 h-100" do %>
              <!--<a href="#" class="d-block mb-4 h-100">-->
                <b style="color: #555555; text-decoration: none;"> <%= product.prodName %></b>
                <br/>
                <!--<img class="img-fluid img-thumbnail" src="http://placehold.it/400x300" alt="">-->
                <%= image_tag(product.pathToImg, :class =>"img-fluid img-thumbnail")%>
                <br/>
                <text style="color: #888888; text-decoration: none;"><%= shorten(product.prodDesc, 50) %></text>
                <br/>
                <h4>
                  <text style="color: #93d671; text-decoration:none;"> <%= number_to_currency(product.price, :unit => '₱') %></text>
                </h4>
              <!--</a>-->
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
      </div>
  </div>
</div>

<div id="thumbnail" class="thumbnail" style="margin-top:2%;">
  <div class="container-fluid">
    <% if @cupcakes_flag %>
      <h2>Cupcakes</h2>
    <% end %>
      <div class="row text-center text-lg-left">
      <% @products.each do |product| %>
        <% if not product.isDeleted? %>
          <% if product.prodCategory.casecmp("Cupcakes") == 0 %>
            <div class="col-lg-3 col-md-3 col-xs-6">
              <%= link_to item_path(product.prodCode), :class => "d-block mb-4 h-100" do %>
              <!--<a href="#" class="d-block mb-4 h-100">-->
                <b style="color: #555555; text-decoration: none;"> <%= product.prodName %></b>
                <br/>
                <!--<img class="img-fluid img-thumbnail" src="http://placehold.it/400x300" alt="">-->
                <%= image_tag(product.pathToImg, :class =>"img-fluid img-thumbnail")%>
                <br/>
                <text style="color: #888888; text-decoration: none;"><%= shorten(product.prodDesc, 50) %></text>
                <br/>
                <h4>
                  <text style="color: #93d671; text-decoration:none;"> <%= number_to_currency(product.price, :unit => '₱') %></text>
                </h4>
              <!--</a>-->
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
      </div>
  </div>
</div>

<div id="thumbnail" class="thumbnail" style="margin-top:2%;">
  <div class="container-fluid">
    <% if @cookies_flag %>
      <h2>Cookies</h2>
    <% end %>
      <div class="row text-center text-lg-left">
      <% @products.each do |product| %>
        <% if not product.isDeleted? %>
          <% if product.prodCategory.casecmp("Cookies") == 0 %>
            <div class="col-lg-3 col-md-3 col-xs-6">
              <%= link_to item_path(product.prodCode), :class => "d-block mb-4 h-100" do %>
              <!--<a href="#" class="d-block mb-4 h-100">-->
                <b style="color: #555555; text-decoration: none;"> <%= product.prodName %></b>
                <br/>
                <!--<img class="img-fluid img-thumbnail" src="http://placehold.it/400x300" alt="">-->
                <%= image_tag(product.pathToImg, :class =>"img-fluid img-thumbnail")%>
                <br/>
                <text style="color: #888888; text-decoration: none;"><%= shorten(product.prodDesc, 50) %></text>
                <br/>
                <h4>
                  <text style="color: #93d671; text-decoration:none;"> <%= number_to_currency(product.price, :unit => '₱') %></text>
                </h4>
              <!--</a>-->
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
      </div>
  </div>
</div>

<div id="thumbnail" class="thumbnail" style="margin-top:2%;">
    <div class="container-fluid">
      <% if @bread_flag %>
        <h2>Bread</h2>
      <% end %>
        <div class="row text-center text-lg-left">
        <% @products.each do |product| %>
          <% if not product.isDeleted? %>
            <% if product.prodCategory.casecmp("Bread") == 0 %>
              <div class="col-lg-3 col-md-3 col-xs-6">
                <%= link_to item_path(product.prodCode), :class => "d-block mb-4 h-100" do %>
              <!--<a href="#" class="d-block mb-4 h-100">-->
                <b style="color: #555555; text-decoration: none;"> <%= product.prodName %></b>
                <br/>
                <!--<img class="img-fluid img-thumbnail" src="http://placehold.it/400x300" alt="">-->
                <%= image_tag(product.pathToImg, :class =>"img-fluid img-thumbnail")%>
                <br/>
                <text style="color: #888888; text-decoration: none;"><%= shorten(product.prodDesc, 50) %></text>
                <br/>
                <h4>
                  <text style="color: #93d671; text-decoration:none;"> <%= number_to_currency(product.price, :unit => '₱') %></text>
                </h4>
              <!--</a>-->
              <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
        </div>
    </div>
</div>
<div id="thumbnail" class="thumbnail" style="margin-top:2%;">
    <div class="container-fluid">
      <% if @brownies_flag %>
        <h2>Brownies</h2>
      <% end %>
        <div class="row text-center text-lg-left">
        <% @products.each do |product| %>
          <% if not product.isDeleted? %>
            <% if product.prodCategory.casecmp("Brownies") == 0 %>
              <div class="col-lg-3 col-md-3 col-xs-6">
                <%= link_to item_path(product.prodCode), :class => "d-block mb-4 h-100" do %>
              <!--<a href="#" class="d-block mb-4 h-100">-->
                <b style="color: #555555; text-decoration: none;"> <%= product.prodName %></b>
                <br/>
                <!--<img class="img-fluid img-thumbnail" src="http://placehold.it/400x300" alt="">-->
                <%= image_tag(product.pathToImg, :class =>"img-fluid img-thumbnail")%>
                <br/>
                <text style="color: #888888; text-decoration: none;"><%= shorten(product.prodDesc, 50) %></text>
                <br/>
                <h4>
                  <text style="color: #93d671; text-decoration:none;"> <%= number_to_currency(product.price, :unit => '₱') %></text>
                </h4>
              <!--</a>-->
              <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
        </div>
    </div>
</div>
<div id="footer" class="footer">
            <div  class="container">
                <div class="row">
                <div class="col-lg-4 col-md-4">
                    <h4>Contact Us</h4>
                    <p>No. 9 Central Ave. New Era, Quezon City</p>
                    <p>TasteBuddy@gmail.com</p>
                    <p>&copy;2018TasteBuddy, All Rights Reserved. </p>
                </div>
                <div class="col-lg-4 col-md-4">
                    <h4>About</h4>
                    <p>Privacy</p>
            <p>Term & Condition</p> 
        </div>
        <div class="col-lg-4 col-md-4">            
            <h4>Stay in touch</h4>
            <input type="email" placeholder="subscribed for Updates">
            <button class="btn btn-success">Suscribes</button>
        </div>
    </div>
</div>
</div>

app/views/main_page/show.html.erb
<br/>
<br/>
<div class= "container">
    <div class="cf">
        <div class="leftcol">
        <%= image_tag(@product.image_url.to_s, size:"300x500") %>
        </div>
        <div class="rightcol" style="align-content: center">    
            <h4><i class='category'><%= @product.prodCategory %></i></h4>
            <h3><b class='name' ><%= @product.prodName %></b></h3>
        </div>
        <br>
        <div class="righttext" style="align-content: left">
            <p><%= @product.prodDesc %></p>
            <p><%= number_to_currency(@product.price, :unit =>'₱') %></p>
        </div>
        <div class ="rightcol"> 
            <%# form_tag("/cart/place", method: "put") do |form| %>
            <%= form_tag(add_to_cart_path, method: "put") do %>
                <div class="field">
                    <%= label_tag :qty, 'Quantity x', style:"display: inline;" %>
                    <%= text_field_tag :qty, 1 %>
                </div>
                <!-- sneaky hidden tag for prod code -->
                <div class="field">
                    <%# label_tag :prodCode %>
                    <%# text_field_tag :prodCode,%>
                    <%= hidden_field_tag :prodCode, @product.prodCode %>
                </div>
                <% if session[:user_id] != nil %>
                    <% puts "[show.html - main_page] user is logged in" %>
                    <%= submit_tag 'Add to Cart', class:'button buttonbuy' %>
                   
                <% end %>
            <% end %>
        </div>
         <% if session[:user_id] == nil %>
            <!-- decoy add to cart button -->
            <% puts "[show.html.erb - main_page] no login found" %>
            <%# button_to "Add to Cart.", must_be_logged_path,  method: :get, class:'button buttonbuy' %>
            <%= button_to "Add to Cart.", dos_must_be_logged_path(@event),  :remote => true , class:'button buttonbuy' %>
         <% end %>
        <!--<div class="clear"></div> idk what this does -->
    </div>
    
        <div class="modal" style="display:none;">
        </div>
</div>